### ISSUE TITLE
Profile page redesign

### ISSUE THREAD

**Issue by eug-vs** [which-ecosystem/which#42]
### TODO:
 - [ ] Improve design as discussed
 - [ ] Allow modifying user information
 - [ ] Display avatar instead on profile icon in header (when logged in)
